import React from 'react';

const TermsOfService = () => {
  return (
    <div>
      <h2>Terms and Conditions of Use</h2>
      <p>This page states the Terms and Conditions under which you, the <cite>History Engine</cite> visitor (&ldquo;You&rdquo;) may use the <cite>History Engine</cite>, which is owned and operated by the University of Richmond (&ldquo;RICHMOND&rdquo;).</p>
      <p>Please read this page carefully. By using the <cite>History Engine</cite>, You agree to be bound by all of the Terms and Conditions set forth below.  If You do not accept these Terms and Conditions, please do not use the <cite>History Engine</cite>. RICHMOND may, in its sole discretion, revise these Terms and Conditions at any time; therefore, You should visit this page periodically to review the Terms and Conditions.</p>
      <p><strong>THE HISTORY ENGINE AND ITS MATERIAL ARE PROVIDED ON AN &ldquo;AS IS&rdquo; BASIS WITHOUT ANY WARRANTIES OF ANY KIND. RICHMOND, TO THE FULLEST EXTENT PERMITTED BY LAW, DISCLAIMS ALL WARRANTIES, INCLUDING THE WARRANTY OF MERCHANTABILITY, NON-INFRINGEMENT OF THIRD PARTIES&rsquo; RIGHTS, AND THE WARRANTY OF FITNESS FOR PARTICULAR PURPOSE.  ALTHOUGH RICHMOND STRIVES TO PROVIDE THOROUGH AND ACCURATE MATERIALS ON ITS SITE, WE MAKE NO WARRANTIES ABOUT THE ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE MATERIAL, SERVICES, SOFTWARE, TEXT, GRAPHICS, AND LINKS.</strong></p>
      <h3>Use of Site Material</h3>
      <p>The contents of the <cite>History Engine</cite>, such as text, essays, articles, graphics, images, and other content (the &ldquo;Site Material&rdquo;) are protected by copyright under both United States and foreign laws.  RICHMOND, however, does not own copyright on article texts found on the <cite>History Engine</cite>&mdash;such copyright is owned by third-party individuals who have submitted their article text to the <cite>History Engine</cite>. To this end, the article text is used by RICHMOND pursuant to a license granted by the third-party submitters. RICHMOND authorizes You to view and download a single copy of the Site Material solely for the purpose of scholarship and research and/or any other use permitted under the doctrine of Fair Use.  Unauthorized use of the Site Material violates copyright, trademark, and other laws. You agree to retain all copyright and other proprietary notices contained in the original Site Material on any copy You make of such material. You may not sell or modify our Site Material or reproduce, display, distribute, or otherwise use the Site Material in any way for any public or commercial purpose. Use of the Site Material on any other History Engine or in a networked environment is prohibited.</p>
      <h3>Trademarks</h3>
      <p>The names, marks and logos appearing included in the Site Material are, unless otherwise noted, trademarks owned by or licensed to RICHMOND.  The use of these marks, except as provided in these Terms and Conditions, is prohibited.  From time to time, RICHMOND makes fair use in the <cite>History Engine</cite> of trademarks owned and used by third parties. Any such marks are clearly noted, and RICHMOND makes no claim to ownership of those marks.</p>
      <h3>Copyright Infringement</h3>
      <p>In accordance with the Digital Millennium Copyright Act (&ldquo;DMCA&rdquo;), Pub. L. 105-304, RICHMOND has designated the following individual to receive notification of alleged copyright infringement on the <cite>History Engine</cite>:</p>
      <address>
        <pre>
          Kevin L. Butterfield 
          Boatwright Memorial Library
          University of Richmond
          Richmond, VA 23173
              
          Tel: 804-289-8456
          Fax: 804-287-1840
          Email: kbutterf@richmond.edu
        </pre>
      </address>
      <p>A claim of copyright infringement must be submitted in writing via either a physical or electronic medium and contain the following:</p>
      <ol>
        <li>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
        <li>Identification of the copyrighted work claimed to have been infringed.</li>
        <li>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit the service provider to locate the material.</li>
        <li>Information sufficient to allow the service provider to contact the complaining party, such as an address, telephone number and, if available, an electronic mail address.</li>
        <li>A statement that the complaining party has a good-faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.</li>
        <li>A statement that the information in the notification is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</li>
      </ol>
      <h3>User Submissions</h3>
      <p>RICHMOND welcomes Your comments on our <cite>History Engine</cite>, however, You acknowledge that if You send us creative suggestions, ideas, notes, drawings, concepts, inventions or other information, (collectively, the &ldquo;Information&rdquo;), the Information shall be deemed, and shall remain RICHMOND&rdquo;s property.   By submission of any Information to us, You assign to us and we shall exclusively own all now known or hereafter existing rights to such Information of every kind and nature throughout the universe and shall be entitled to unrestricted use of the Information for any purpose whatsoever, commercial or otherwise, without compensation to the provider of the information.</p>
      <p>As a user of the <cite>History Engine</cite>, You are responsible for own Your own communications and are responsible for the consequences of their posting. Therefore, do not do any of the following things: transmit to us material that is copyrighted, unless You are the copyright owner or have the permission of the copyright owner to post it; send material that reveals trade secrets, unless You own them or have the permission of the owner; send material that infringes on any other intellectual property rights of others or on the privacy or publicity rights of others; send material that is obscene, defamatory, threatening, harassing, abusive, hateful, or embarrassing to another user or any other person or entity; send sexually-explicit images; send advertisements or solicitations of business; send chain letters or pyramid schemes; or impersonate another person.</p>
      <p>RICHMOND reserves the right to expel users and prevent their further access to the <cite>History Engine</cite> for violating these terms or the law and reserves the right to remove any communications from this Site.  The violation of any of the terms and conditions set forth on this Legal Terms and Conditions page shall result in the immediate revocation of your license to use the Site Material and obligates You to immediately destroy any copies of the Site Material in your possession.</p>
      <h3>Limitation of Liability</h3>
      <p>Although RICHMOND strives for accuracy in all elements of the Site Material, it may contain inaccuracies or typographical errors.  Additionally, while users of this Site are bound by these terms and conditions not to submit false material, RICHMOND cannot be responsible for the violation of these terms by users, or for the reliance by users upon false or misleading material submitted by other users.  RICHMOND makes no representations about the accuracy, reliability, completeness, or timeliness of the material on the <cite>History Engine</cite> or about the results to be obtained from using the History Engine. You use the <cite>History Engine</cite> and its material at your own risk.</p>
      <p><strong>RICHMOND DOES NOT WARRANT THAT THE HISTORY ENGINE WILL OPERATE ERROR-FREE OR THAT THE HISTORY ENGINE AND ITS SERVER ARE FREE OF COMPUTER VIRUSES OR OTHER HARMFUL MATERIAL. IF YOUR USE OF THE HISTORY ENGINE OR THE SITE&rsquo;S MATERIAL RESULTS IN ANY COSTS OR EXPENSES, INCLUDING, WITHOUT LIMITATION, THE NEED FOR SERVICING OR REPLACING EQUIPMENT OR DATA, RICHMOND SHALL NOT BE RESPONSIBLE FOR THOSE COSTS OR EXPENSES.</strong></p>
      <h3>Disclaimer of Consequential Damages</h3>
      <p><strong>IN NO EVENT SHALL RICHMOND, ITS AFFILIATES, OR ANY THIRD PARTIES MENTIONED ON THE SITE BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) RESULTING FROM THE USE OR INABILITY TO USE MATERIAL ON THE HISTORY ENGINE OR SITES LINKED TO THE HISTORY ENGINE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT RICHMOND IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</strong></p>
      <h3>Links</h3>
      <p>The History Engine may contain links to History Engines owned by third parties. These links are provided solely as a convenience to You and are not an endorsement by RICHMOND of the contents on those other sites.  RICHMOND is not responsible for the content of any linked sites and makes no representations regarding the content or accuracy of materials on such sites. If You decide to visit any third-party sites using links from the <cite>History Engine</cite>, You do so at your own risk.</p>
      <h3>Privacy</h3>
      <p>At RICHMOND, your privacy is important to us.  RICHMOND does not collect personally-identifying information about You (such as Your name, address, telephone number, or e-mail address) unless You voluntarily submit that information to us through one of our Contact pages, or by e-mail or other means.  We treat any information You submit through the <cite>History Engine</cite>, as confidential and do not sell or otherwise disclose such information to third parties except under strict contracts involving the enhancement of our <cite>History Engine</cite>.</p>
      <p>When You visit our <cite>History Engine</cite>, we may automatically collect certain non-identifying information about you, such as the type of browser or computer operating system You use or the domain name of the History Engine from which You linked to us.  In addition, we may store some information on your computer&rdquo;s hard drive as a &ldquo;cookie&rdquo; or similar type of file. We use this information internally, to help us enhance the efficiency and usefulness of the <cite>History Engine</cite>.  If You object to this, please consult your Browser&rsquo;s documentation for information on erasing or blocking cookies.</p>
      <p>Any information we gather, whether voluntarily provided by You or automatically collected, may be used for our internal purposes but will not be sold or otherwise disclosed to third parties for any purpose.  Notwithstanding any other statements or representations here or elsewhere on our <cite>History Engine</cite>, we reserve our right to disclose any information in our possession if we are required to do so by law, or we believe, in good faith, that such a disclosure is necessary to comply with the law, defend our rights or property, or to respond to an emergency situation.</p>
      <p>If You are concerned about the information You have provided to us, or would like to review, update or delete that information, please write Robert K. Nelson at rnelson2@richmond.edu. We will make reasonable efforts to comply with your wishes.</p>
      <h3>Miscellaneous</h3>
      <p>The <cite>History Engine</cite> originates from Richmond, Virginia.  RICHMOND does not claim that the Site Materials on the <cite>History Engine</cite> are appropriate or may be used outside of the United States.  Access to the Site Materials may not be legal by certain persons or in certain countries. If You access the <cite>History Engine</cite> from outside of the United States, You do so at your own risk and are responsible for compliance with the laws of your jurisdiction.</p>
      <p>These Terms and Conditions are governed by the substantive laws of the Commonwealth of Virginia, without respect to its conflict of laws principles. You agree to submit to the jurisdiction of the courts situated in the Commonwealth of Virginia with respect to any dispute, disagreement, or cause of action related to or involving the <cite>History Engine</cite>. If any provision is found to be invalid by any court having competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms and Conditions, which shall remain in full force and effect. No waiver of any of these Terms and Conditions shall be deemed a further or continuing waiver of such term or any other term. Except as expressly provided elsewhere in our <cite>History Engine</cite>, these Terms and Conditions constitute the entire agreement between You and RICHMOND with respect to your use of the <cite>History Engine</cite>.</p>  
    </div>
  );
};

export default TermsOfService;
